[build]
  command = "npm run build"
  publish = "dist" # or "build" depending on your frontend framework

# Redirect API calls to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://backend-job-board.onrender.com/api/:splat"
  status = 200
  force = true

# Ensure SPA routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200